###### 공통
### Search Store
GET http://localhost:8082/store/search?address=인계동 1100&maxDistance=1000&sort=distance
Content-Type: application/json

### Store info
GET http://localhost:8082/store/getInfo?id=1
Content-Type: application/json

### Store reservation List
GET http://localhost:8082/store/reservations?id=1
Content-Type: application/json

### Store review List
GET http://localhost:8082/store/reviews?id=1
Content-Type: application/json

######## User
### 예약 요청
POST http://localhost:8082/user/reservation
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJRRFcvQjJ6M2w2NlJpZWNNOHpYbEtTZkxWaTNqalhIdjN1YVVHazlLWHJzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTY4NzE1OTAxOSwiZXhwIjoxNjg3MjQ1NDE5fQ.Mzoh6kMXrIOlqnDgF8Ep9Dh1yNwXiSUuEVpS_6sGIBc

{
  "dateTime": "2023-06-20 16:30",
  "storeId": 1
}

### 리뷰 등록
POST http://localhost:8082/user/reservation/review?id=2
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJRRFcvQjJ6M2w2NlJpZWNNOHpYbEtTZkxWaTNqalhIdjN1YVVHazlLWHJzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTY4NzE1OTAxOSwiZXhwIjoxNjg3MjQ1NDE5fQ.Mzoh6kMXrIOlqnDgF8Ep9Dh1yNwXiSUuEVpS_6sGIBc

{
  "rating": 5.0,
  "text": "test review2"
}

####### Partner
### store 등록
POST http://localhost:8082/partner/store
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZHFFeEN6VC9mNEtEZWhIVnluM2tlYWx3Nkd1VlVqdi81MFQwUDdrVStvPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiUEFSVE5FUiIsImlhdCI6MTY4NzE1ODM5MCwiZXhwIjoxNjg3MjQ0NzkwfQ.6-uonjFjkwQlfhHNvMJFebp9z71YHI2MG_wNs-nKBEo

{
  "address": "인계동 1119",
  "name": "fString2",
  "text": "전문점1"
}

### reservation 승인 상태 변경
PUT http://localhost:8082/partner/reservation?id=2
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZHFFeEN6VC9mNEtEZWhIVnluM2tlYWx3Nkd1VlVqdi81MFQwUDdrVStvPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiUEFSVE5FUiIsImlhdCI6MTY4NzE1ODM5MCwiZXhwIjoxNjg3MjQ0NzkwfQ.6-uonjFjkwQlfhHNvMJFebp9z71YHI2MG_wNs-nKBEo

### kiosk - checkValidReservation 체크인 가능한 예약 정보인지 확인
PUT http://localhost:8082/partner/1/checkin?id=2
Content-Type: application/json