###### 공통
### Search Store
GET http://localhost:8082/store/search?address=인계동 1100&maxDistance=1000&sort=rating
Content-Type: application/json

### Store info
GET http://localhost:8082/store/getInfo?id=2
Content-Type: application/json

### Store reservation List
GET http://localhost:8082/store/reservations?id=1
Content-Type: application/json

### Store review List
GET http://localhost:8082/store/reviews?id=2
Content-Type: application/json

######## User
### 예약 요청
POST http://localhost:8082/user/reservation
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJHWGhFdEw0ZzE1LzZNQ2xyaitjRjkyQXlxV28ydlBINGhIYTA2Q3M3NWQ4PSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTY4NzQ0MTM4NSwiZXhwIjoxNjg3NTI3Nzg1fQ.8hFosM20I-25aSrT34AzuzO8gKXegqb4LS3nrGxOauU

{
  "dateTime": "2023-06-23 16:30",
  "storeId": 1
}

### 리뷰 등록
POST http://localhost:8082/user/reservation/review?id=2
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJHWGhFdEw0ZzE1LzZNQ2xyaitjRjkyQXlxV28ydlBINGhIYTA2Q3M3NWQ4PSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTY4NzQ0MTM4NSwiZXhwIjoxNjg3NTI3Nzg1fQ.8hFosM20I-25aSrT34AzuzO8gKXegqb4LS3nrGxOauU

{
  "rating": 3.0,
  "text": "test review2"
}

####### Partner
### store 등록
POST http://localhost:8082/partner/store
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKS0J2a3NOMlhqb09qd25qamRNdkg3Z1BPMWsrb2k2SVJ3a2Judlk3UkVNPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiUEFSVE5FUiIsImlhdCI6MTY4NzQ0MTMyMiwiZXhwIjoxNjg3NTI3NzIyfQ.kn0Epb4qQnnayjaXHkVrKfVjAC2mZrMwVCiMMpjwzns

{
  "address": "인계동 1120",
  "name": "aString2",
  "text": "전문점1"
}

### reservation 승인
PUT http://localhost:8082/partner/reservation/approval?id=1
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKS0J2a3NOMlhqb09qd25qamRNdkg3Z1BPMWsrb2k2SVJ3a2Judlk3UkVNPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiUEFSVE5FUiIsImlhdCI6MTY4NzQ0MTMyMiwiZXhwIjoxNjg3NTI3NzIyfQ.kn0Epb4qQnnayjaXHkVrKfVjAC2mZrMwVCiMMpjwzns

### reservation 거절
PUT http://localhost:8082/partner/reservation/refuse?id=1
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKS0J2a3NOMlhqb09qd25qamRNdkg3Z1BPMWsrb2k2SVJ3a2Judlk3UkVNPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiUEFSVE5FUiIsImlhdCI6MTY4NzQ0MTMyMiwiZXhwIjoxNjg3NTI3NzIyfQ.kn0Epb4qQnnayjaXHkVrKfVjAC2mZrMwVCiMMpjwzns

######## kiosk - 체크인 가능한 예약 정보인지 확인. 체크인 시 서버에 알림
PUT http://localhost:8082/kiosk/checkin
Content-Type: application/json

{
  "reservationId": 1,
  "storeId": 1
}