####### Partner
### store 등록
POST http://localhost:8082/partner/store
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZHFFeEN6VC9mNEtEZWhIVnluM2tlYWx3Nkd1VlVqdi81MFQwUDdrVStvPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiUEFSVE5FUiIsImlhdCI6MTY4NzAwNzU0NiwiZXhwIjoxNjg3MDkzOTQ2fQ.OR91cuYB3NoehSej104V5Lb7D7a1nMZCJ9BYq_bPcyQ

{
  "address": "인계동 1119",
  "name": "fString2",
  "text": "전문점1"
}

###### 공통
### Search Store
GET http://localhost:8082/store/search?address=인계동 1100&maxDistance=1000&sort=distance
Content-Type: application/json

### Store info
GET http://localhost:8082/store/getInfo?id=1
Content-Type: application/json



######## User
### 예약 요청
POST http://localhost:8082/user/reservation
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJRRFcvQjJ6M2w2NlJpZWNNOHpYbEtTZkxWaTNqalhIdjN1YVVHazlLWHJzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTY4NzAwNzU4MCwiZXhwIjoxNjg3MDkzOTgwfQ.RnsTeJ15S9tb08yLf4XDcC3S5uZ7PLZuYfuuaINauuM

{
  "dateTime": "2023-06-17 14:20",
  "storeId": 1
}
